# Summary
A simple web scraper a Coronavirus tracker. Grabs data from a table and loads into a pandas dataframe, ready to be exported or analyzed.

In [1]:
# imports
import requests
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup

# pandas display options
pd.set_option('display.max_rows', 1000)
pd.set_option('display.max_columns', 1000)

In [2]:
# url -> html
url = 'https://www.worldometers.info/coronavirus/'
r = requests.get(url)
html = r.text
soup = BeautifulSoup(html)

In [3]:
# find table
table = soup.find('table', id='main_table_countries_today')

In [4]:
# get headers
headers = []
th = table.find_all('th')
for h in th:
    headers.append(h.text)

In [5]:
# create array from each row
rows = table.tbody.find_all('tr')
array = []
for i in range(len(rows)):
#for r in rows:
    row = []
    cells = rows[i].find_all('td')
    #cells = r.find_all('td')
    for cell in cells:
        a = cell.find_all('a')
        row.append(cell.text)
    array.append(row)
array = np.array(array)

In [6]:
# put into dataframe
df = pd.DataFrame(array, columns=headers)
df = df.loc[8:]
df.set_index('#', inplace=True)
df

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotÂ Cases/1M pop,Deaths/1M pop,TotalTests,Tests/\n1M pop\n,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
#,,,,,,,,,,,,,,,,,,,,,
1,USA,"106,524,168",,"1,158,842",,"104,423,700",,"941,626","1,517","318,168","3,461","1,176,315,905","3,513,433","334,805,269",North America,3,289,0,,,"2,812"
2,India,"44,869,684",,"531,258",,"44,272,256",,"66,170",N/A,"31,899",378,"924,617,164","657,327","1,406,631,776",Asia,31,"2,648",2,,,47
3,France,"39,931,043",,"166,164",,"39,625,636",,"139,243",869,"608,849","2,534","271,490,188","4,139,547","65,584,518",Europe,2,395,0,,,"2,123"
4,Germany,"38,392,366",,"172,428",,"38,173,500","+2,900","46,438",N/A,"457,686","2,056","122,332,384","1,458,359","83,883,596",Europe,2,486,1,,,554
5,Brazil,"37,407,232",,"701,215",,"36,249,161",,"456,856",N/A,"173,701","3,256","63,776,166","296,146","215,353,593",South America,6,307,3,,,"2,121"
6,Japan,"33,628,545","+10,074","74,338",+24,"21,725,273",,"11,828,934",59,"267,776",592,"99,493,194","792,239","125,584,838",Asia,4,"1,689",1,80,0.2,"94,191"
7,S. Korea,"31,053,459","+13,596","34,408",+7,"30,809,499","+4,340","209,552",142,"604,978",670,"15,804,065","307,892","51,329,899",Asia,2,"1,492",3,265,0.1,"4,082"
8,Italy,"25,737,170",,"189,391",,"25,413,901",,"133,878",83,"427,082","3,143","270,717,229","4,492,280","60,262,770",Europe,2,318,0,,,"2,222"
9,UK,"24,555,629",,"221,943",,"24,239,333",,"94,353",N/A,"358,487","3,240","522,526,476","7,628,357","68,497,907",Europe,3,309,0,,,"1,377"
10,Russia,"22,796,845","+7,116","398,007",+33,"22,189,176","+7,409","209,662",N/A,"156,351","2,730","273,400,000","1,875,095","145,805,947",Europe,6,366,1,49,0.2,"1,438"
11,Turkey,"17,232,066",,"102,174",,N/A,N/A,N/A,,"201,399","1,194","162,743,369","1,902,052","85,561,976",Asia,5,837,1,,,"4,024"
12,Spain,"13,813,830",,"120,606",,"13,659,874",,"33,350",231,"295,678","2,582","471,036,328","10,082,298","46,719,142",Europe,3,387,0,,,714
13,Vietnam,"11,540,722","+2,474","43,186",,"10,616,193",+206,"881,343",91,"116,628",436,"85,826,548","867,342","98,953,541",Asia,9,"2,291",1,25,,"8,907"
14,Australia,"11,411,267","+4,211","20,154",+15,"11,342,700","+4,084","48,413",61,"437,737",773,"78,835,048","3,024,116","26,068,792",Australia/Oceania,2,"1,293",0,162,0.6,"1,857"
15,Taiwan,"10,239,998",,"19,005",,"10,220,993",,0,,"428,656",796,"30,742,304","1,286,903","23,888,595",Asia,2,"1,257",1,,,
16,Argentina,"10,044,957",,"130,472",,"9,914,485",,0,363,"218,320","2,836","35,716,069","776,264","46,010,234",South America,5,353,1,,,
17,Netherlands,"8,610,372",,"22,992",,"8,584,137",+630,"3,243",53,"500,270","1,336","25,984,435","1,509,718","17,211,447",Europe,2,749,1,,,188
18,Iran,"7,603,697",,"145,837",,"7,342,490",,"115,370",407,"88,392","1,695","55,353,767","643,478","86,022,837",Asia,11,590,2,,,"1,341"
19,Mexico,"7,572,705","+1,949","333,732",+14,"6,817,972",+871,"421,001",N/A,"57,560","2,537","19,870,676","151,036","131,562,772",North America,17,394,7,15,0.1,"3,200"
20,Indonesia,"6,762,804",+904,"161,170",+5,"6,590,632",+778,"11,002",N/A,"24,228",577,"114,158,919","408,975","279,134,505",Asia,41,"1,732",2,3,0.02,39
21,Poland,"6,511,432",+455,"119,513",+9,"5,335,940",,"1,055,979",696,"172,535","3,167","38,632,102","1,023,644","37,739,785",Europe,6,316,1,12,0.2,"27,981"
22,Colombia,"6,364,014",,"142,706",,"6,186,783",,"34,525",342,"123,542","2,770","36,951,507","717,327","51,512,762",South America,8,361,1,,,670
23,Austria,"6,058,265",+727,"22,316",+1,"6,022,914",+368,"13,035",55,"668,188","2,461","211,273,524","23,302,116","9,066,710",Europe,1,406,0,80,0.1,"1,438"
24,Greece,"5,993,868",,"36,673",,"5,933,037",,"24,158",115,"580,990","3,555","102,228,365","9,909,078","10,316,637",Europe,2,281,0,,,"2,342"
25,Portugal,"5,577,825",,"26,480",,"5,547,029",,"4,316",61,"550,050","2,611","46,082,209","4,544,341","10,140,570",Europe,2,383,0,,,426
26,Ukraine,"5,502,019",,"111,912",,"5,354,042",,"36,065",,"127,385","2,591","32,603,805","754,855","43,192,122",Europe,8,386,1,,,835
27,Chile,"5,280,738",,"64,497",,"5,214,999",,"1,242",67,"274,321","3,350","49,282,442","2,560,101","19,250,195",South America,4,298,0,,,65
28,Malaysia,"5,062,060",,"37,000",,"5,010,543",,"14,517",14,"152,559","1,115","68,344,917","2,059,756","33,181,072",Asia,7,897,0,,,438
29,Israel,"4,820,016",,"12,465",,"4,798,473",,"9,078",21,"516,836","1,337","41,373,364","4,436,346","9,326,000",Asia,2,748,0,,,973
30,Belgium,"4,790,564",,"34,188",,"4,732,095","+2,938","24,281",43,"410,563","2,930","36,997,339","3,170,763","11,668,278",Europe,2,341,0,,,"2,081"
31,DPRK,"4,772,813",,74,,"4,772,739",,0,,"183,636",3,,,"25,990,679",Asia,5,"351,225",,,,
32,Thailand,"4,729,402",,"33,942",,"4,692,636",,"2,824",N/A,"67,487",484,"17,270,775","246,450","70,078,203",Asia,15,"2,065",4,,,40
33,Canada,"4,641,301",,"52,247",,"4,569,105","+1,098","19,949",99,"120,904","1,361","66,343,123","1,728,207","38,388,419",North America,8,735,1,,,520
34,Czechia,"4,639,128",+204,"42,745",,"4,592,202",+66,"4,181",11,"432,078","3,981","57,162,427","5,323,980","10,736,784",Europe,2,251,0,19,,389
35,Peru,"4,499,001",,"220,057",,"4,275,125",,"3,819",32,"133,564","6,533","38,477,677","1,142,306","33,684,208",South America,7,153,1,,,113
36,Switzerland,"4,401,379",,"14,452",,"4,381,603",,"5,324",39,"501,660","1,647","23,833,472","2,716,487","8,773,637",Europe,2,607,0,,,607
37,Philippines,"4,087,964",+553,"66,444",,"4,016,863","+3,161","4,657",162,"36,335",591,"34,956,695","310,701","112,508,994",Asia,28,"1,693",3,5,,41
38,South Africa,"4,076,463",,"102,595",,"3,912,506",,"61,362",192,"67,095","1,689","26,795,090","441,027","60,756,135",Africa,15,592,2,,,"1,010"
39,Romania,"3,382,756",,"68,001",,"3,306,824",,"7,931",134,"177,747","3,573","27,180,208","1,428,182","19,031,335",Europe,6,280,1,,,417
40,Denmark,"3,180,009",+78,"8,502",+4,"3,170,394",+71,"1,113",19,"544,993","1,457","129,259,382","22,152,612","5,834,950",Europe,2,686,0,13,0.7,191
41,Hong Kong,"2,887,756",+234,"13,500",+3,"2,870,634",+31,"3,622",28,"379,753","1,775","76,127,725","10,011,143","7,604,299",Asia,3,563,0,31,0.4,476
42,Sweden,"2,704,966",,"23,988",,"2,677,057",,"3,921",8,"264,700","2,347","19,500,873","1,908,301","10,218,971",Europe,4,426,1,,,384
43,Serbia,"2,530,489",,"18,007",,"2,501,348",,"11,134",11,"292,440","2,081","12,737,966","1,472,084","8,653,016",Europe,3,481,1,,,"1,287"
44,Iraq,"2,465,545",,"25,375",,"2,439,497",,673,21,"58,474",602,"19,544,451","463,523","42,164,965",Asia,17,"1,662",2,,,16
45,Singapore,"2,314,707",,"1,727",,"2,149,583",,"163,397",2,"389,449",291,"24,756,666","4,165,302","5,943,546",Asia,3,"3,442",0,,,"27,492"
46,New Zealand,"2,300,696",,"4,076",,"2,283,778",,"12,842",,"469,702",832,"7,768,604","1,586,011","4,898,203",Australia/Oceania,2,"1,202",1,,,"2,622"
47,Hungary,"2,200,739",,"48,838",,"2,147,822",,"4,079",13,"229,094","5,084","11,394,556","1,186,160","9,606,259",Europe,4,197,1,,,425
48,Bangladesh,"2,038,129",,"29,446",,"1,998,448",,"10,235",N/A,"12,140",175,"15,254,399","90,862","167,885,689",Asia,82,"5,701",11,,,61
49,Slovakia,"1,866,264",+36,"21,159",+3,"1,844,626",+45,479,22,"341,795","3,875","7,424,814","1,359,808","5,460,193",Europe,3,258,1,7,0.5,88
50,Georgia,"1,838,936",,"17,049",,"1,776,548",,"45,339",,"463,355","4,296","16,920,079","4,263,340","3,968,738",Asia,2,233,0,,,"11,424"
51,Jordan,"1,746,997",,"14,122",,"1,731,007",,"1,868",59,"169,597","1,371","17,201,885","1,669,945","10,300,869",Asia,6,729,1,,,181
52,Ireland,"1,708,933",,"8,810",,"1,697,366",+881,"2,757",19,"340,411","1,755","13,083,449","2,606,161","5,020,199",Europe,3,570,0,,,549
53,Pakistan,"1,580,557",+20,"30,656",,"1,538,689",,"11,212",14,"6,887",134,"30,570,862","133,213","229,488,994",Asia,145,"7,486",8,0.09,,49
54,Norway,"1,482,587",,"5,213",,"1,476,208",,"1,166",20,"269,005",946,"11,002,430","1,996,315","5,511,370",Europe,4,"1,057",1,,,212
55,Finland,"1,471,205",,"9,215",,"1,457,175",,"4,815",21,"264,845","1,659","12,069,254","2,172,699","5,554,960",Europe,4,603,0,,,867
56,Kazakhstan,"1,411,121",+47,"13,848",,"1,383,020",,"14,253",24,"73,477",721,"11,575,012","602,707","19,205,043",Asia,14,"1,387",2,2,,742
57,Slovenia,"1,342,883",+75,"7,100",,"1,328,006",,"7,777",8,"646,228","3,417","2,847,701","1,370,382","2,078,034",Europe,2,293,1,36,,"3,742"
58,Lithuania,"1,317,679",+122,"9,659",,"1,304,894",+218,"3,126",2,"495,050","3,629","10,432,153","3,919,345","2,661,708",Europe,2,276,0,46,,"1,174"
59,Bulgaria,"1,303,038",,"38,303",,"1,261,856",,"2,879",39,"190,375","5,596","11,162,648","1,630,870","6,844,597",Europe,5,179,1,,,421
60,Morocco,"1,272,889",,"16,296",,"1,256,151",,442,3,"33,699",431,"13,001,033","344,191","37,772,756",Africa,30,"2,318",3,,,12
61,Croatia,"1,271,818",,"18,129",,"1,253,060",,629,5,"313,311","4,466","5,567,583","1,371,567","4,059,286",Europe,3,224,1,,,155
62,Guatemala,"1,247,237",,"20,189",,"1,226,129",,919,5,"67,113","1,086","7,179,223","386,311","18,584,039",North America,15,921,3,,,49
63,Lebanon,"1,235,933",,"10,888",,"1,087,587",,"137,458",74,"184,886","1,629","4,795,578","717,380","6,684,849",Asia,5,614,1,,,"20,563"
64,Costa Rica,"1,226,315",,"9,326",,"860,711",,"356,278",52,"236,633","1,800","4,659,757","899,158","5,182,354",North America,4,556,1,,,"68,748"
65,Bolivia,"1,196,717",,"22,376",,"1,165,652",,"8,689",220,"99,787","1,866","2,705,422","225,590","11,992,656",South America,10,536,4,,,725
66,Tunisia,"1,152,483",,"29,378",,N/A,N/A,N/A,44,"95,668","2,439","5,009,089","415,807","12,046,656",Africa,10,410,2,,,"1,088"
67,Cuba,"1,113,074",,"8,530",,"1,104,413",,131,2,"98,453",754,"14,344,078","1,268,753","11,305,652",North America,10,"1,325",1,,,12
68,UAE,"1,061,047",,"2,349",,"1,042,541",,"16,157",,"105,244",233,"200,156,954","19,853,325","10,081,785",Asia,10,"4,292",0,,,"1,603"
69,Ecuador,"1,059,993",,"36,017",,"1,022,992",,984,759,"58,520","1,988","3,082,403","170,173","18,113,361",South America,17,503,6,,,54
70,Uruguay,"1,037,095",,"7,621",,"1,028,996",,478,18,"296,651","2,180","6,114,822","1,749,083","3,496,016",South America,3,459,1,,,137
71,Panama,"1,036,100",,"8,618",,"1,026,868",,614,16,"232,990","1,938","7,636,393","1,717,215","4,446,964",North America,4,516,1,,,138
72,Mongolia,"1,007,966",,"2,179",,"1,005,736",,51,192,"298,384",645,"4,030,048","1,193,000","3,378,078",Asia,3,"1,550",1,,,15
73,Nepal,"1,002,537",+64,"12,026",+1,"990,097",+46,414,,"33,168",398,"6,029,966","199,499","30,225,582",Asia,30,"2,513",5,2,0.03,14
74,Belarus,"994,037",,"7,118",,"985,592",,"1,327",,"105,381",755,"13,646,641","1,446,722","9,432,800",Europe,9,"1,325",1,,,141
75,Latvia,"977,481",+23,"6,315",+1,"970,786",+44,380,13,"528,700","3,416","7,872,643","4,258,160","1,848,837",Europe,2,293,0,12,0.5,206
76,Saudi Arabia,"839,069",+116,"9,640",+1,"825,807",+244,"3,622",84,"23,408",269,"45,408,299","1,266,799","35,844,909",Asia,43,"3,718",1,3,0.03,101
77,Azerbaijan,"831,065",+24,"10,222",+2,"820,480",+81,363,,"80,684",992,"7,581,147","736,019","10,300,205",Asia,12,"1,008",1,2,0.2,35
78,Paraguay,"809,269",,"19,906",,N/A,N/A,N/A,7,"110,770","2,725","2,657,506","363,751","7,305,843",South America,9,367,3,,,"12,462"
79,Bahrain,"719,227",,"1,560",,"717,166",,501,1,"403,158",874,"10,822,553","6,066,511","1,783,983",Asia,2,"1,144",0,,,281
80,Sri Lanka,"672,123",,"16,835",,"655,264",,24,,"31,152",780,"6,486,117","300,619","21,575,842",Asia,32,"1,282",3,,,1
81,Kuwait,"665,527",,"2,570",,"660,237",,"2,720",,"151,935",587,"8,455,743","1,930,391","4,380,326",Asia,7,"1,704",1,,,621
82,Dominican Republic,"660,961",,"4,384",,"644,785",,"11,792",4,"59,781",397,"3,740,928","338,350","11,056,370",North America,17,"2,522",3,,,"1,067"
83,Cyprus,"656,904",,"1,350",,"653,364",,"2,190",60,"536,955","1,103","9,640,118","7,879,860","1,223,387",Asia,2,906,0,,,"1,790"
84,Myanmar,"634,243",,"19,490",,"614,656",,97,,"11,484",353,"10,259,586","185,771","55,227,143",Asia,87,"2,834",5,,,2
85,Palestine,"621,008",,"5,404",,"615,445",,159,17,"116,173","1,011","3,078,533","575,907","5,345,541",Asia,9,989,2,,,30
86,Moldova,"619,973",,"12,106",,"504,142",,"103,725",49,"154,485","3,017","3,216,305","801,437","4,013,171",Europe,6,332,1,,,"25,846"
87,Estonia,"617,587",,"2,986",,"524,990",,"89,611",3,"467,193","2,259","3,700,597","2,799,432","1,321,910",Europe,2,443,0,,,"67,789"
88,Venezuela,"552,548",,"5,856",,"546,447",,245,31,"18,880",200,"3,359,014","114,771","29,266,991",South America,53,"4,998",9,,,8
89,Egypt,"515,970",,"24,613",,"442,182",,"49,175",122,"4,860",232,"3,693,367","34,792","106,156,692",Africa,206,"4,313",29,,,463
90,Libya,"507,250",,"6,437",,"500,807",,6,,"72,045",914,"2,483,848","352,782","7,040,745",Africa,14,"1,094",3,,,0.9
91,Qatar,"506,323",,690,,"504,400",,"1,233",44,"169,912",232,"4,065,369","1,364,257","2,979,915",Asia,6,"4,319",1,,,414
92,Ethiopia,"500,804",,"7,574",,"487,866",,"5,364",1,"4,145",63,"5,535,355","45,818","120,812,698",Africa,241,"15,951",22,,,44
93,RÃ©union,"486,588",,921,,"418,572",,"67,095",10,"535,854","1,014","1,603,660","1,766,027","908,061",Africa,2,986,1,,,"73,888"
94,Honduras,"472,533",,"11,112",,N/A,N/A,N/A,105,"46,230","1,087","1,652,947","161,717","10,221,247",North America,22,920,6,,,"32,176"
95,Armenia,"448,980",,"8,746",,"435,162",,"5,072",,"151,072","2,943","3,242,901","1,091,164","2,971,966",Asia,7,340,1,,,"1,707"
96,Bosnia and Herzegovina,"402,709",,"16,332",,"379,084",,"7,293",,"123,937","5,026","1,884,721","580,036","3,249,317",Europe,8,199,2,,,"2,244"
97,Oman,"399,449",,"4,628",,"384,669",,"10,152",2,"75,028",869,"25,000,000","4,695,724","5,323,993",Asia,13,"1,150",0,,,"1,907"
98,North Macedonia,"347,965",,"9,671",,"337,068",,"1,226",,"167,186","4,647","2,226,216","1,069,626","2,081,304",Europe,6,215,1,,,589
99,Zambia,"343,803",,"4,058",,"339,632",,113,,"17,658",208,"4,000,548","205,470","19,470,234",Africa,57,"4,798",5,,,6
100,Kenya,"343,005",,"5,688",,"337,294",,23,1,"6,102",101,"3,967,062","70,569","56,215,221",Africa,164,"9,883",14,,,0.4
101,Albania,"334,726",,"3,602",,"329,428",,"1,696",,"116,777","1,257","1,941,032","677,173","2,866,374",Europe,9,796,1,,,592
102,Botswana,"329,841",,"2,801",,"327,039",,1,1,"135,116","1,147","2,026,898","830,300","2,441,162",Africa,7,872,1,,,0.4
103,Luxembourg,"297,757",,"1,133",,"288,991",,"7,633",,"463,528","1,764","4,412,567","6,869,188","642,371",Europe,2,567,0,,,"11,883"
104,Montenegro,"291,057",,"2,823",,"287,506",,728,6,"463,503","4,496","2,743,547","4,369,053","627,950",Europe,2,222,0,,,"1,159"
105,Brunei,"285,740",,225,,"243,601",,"41,914",3,"641,491",505,"717,784","1,611,437","445,431",Asia,2,"1,980",1,,,"94,098"
106,Algeria,"271,666",,"6,881",,"182,930",,"81,855",,"5,990",152,"230,861","5,091","45,350,148",Africa,167,"6,591",196,,,"1,805"
107,Nigeria,"266,675",,"3,155",,"259,953",,"3,567",11,"1,230",15,"5,708,974","26,339","216,746,934",Africa,813,"68,700",38,,,16
108,Zimbabwe,"264,613",,"5,685",,"258,860",,68,12,"17,260",371,"2,525,756","164,744","15,331,428",Africa,58,"2,697",6,,,4
109,Uzbekistan,"252,514",,"1,637",,"241,486",,"9,391",23,"7,344",48,"1,377,915","40,077","34,382,084",Asia,136,"21,003",25,,,273
110,Mozambique,"233,334",,"2,242",,"228,805",,"2,287",11,"7,052",68,"1,371,127","41,437","33,089,461",Africa,142,"14,759",24,,,69
111,Martinique,"229,807",,"1,098",,N/A,N/A,N/A,12,"614,314","2,935","828,928","2,215,870","374,087",North America,2,341,0,,,"611,101"
112,Laos,"218,065",+13,758,,N/A,N/A,N/A,,"29,149",101,"1,233,207","164,845","7,481,023",Asia,34,"9,869",6,2,,"28,024"
113,Afghanistan,"213,976",+81,"7,896",,"193,122",+3,"12,958",45,"5,250",194,"1,229,609","30,171","40,754,388",Asia,190,"5,161",33,2,,318
114,Iceland,"209,191",,229,,N/A,N/A,N/A,2,"605,661",663,"1,996,384","5,780,036","345,393",Europe,2,"1,508",0,,,"385,871"
115,Kyrgyzstan,"206,866",,"2,991",,"196,406",,"7,469",131,"30,746",445,"1,907,195","283,460","6,728,271",Asia,33,"2,250",4,,,"1,110"
116,Guadeloupe,"202,364",,"1,015",,N/A,N/A,N/A,19,"506,171","2,539","938,039","2,346,306","399,794",North America,2,394,0,,,"498,004"
117,El Salvador,"201,785",,"4,230",,"179,410",,"18,145",8,"30,805",646,"2,610,114","398,467","6,550,389",North America,32,"1,549",3,,,"2,770"
118,Trinidad and Tobago,"191,350",,"4,387",,"186,918",,45,8,"136,039","3,119","911,009","647,674","1,406,585",North America,7,321,2,,,32
119,Maldives,"186,042",,311,,"163,687",,"22,044",25,"343,895",575,"2,213,831","4,092,223","540,985",Asia,3,"1,740",0,,,"40,748"
120,Ghana,"171,619",,"1,462",,"170,131",,26,2,"5,298",45,"2,535,895","78,279","32,395,450",Africa,189,"22,158",13,,,0.8
121,Namibia,"171,222",,"4,090",,"167,099",,33,,"65,008","1,553","1,062,663","403,460","2,633,874",Africa,15,644,2,,,13
122,Uganda,"170,634",,"3,632",,"100,431",,"66,571",3,"3,523",75,"3,012,408","62,198","48,432,863",Africa,284,"13,335",16,,,"1,375"
123,Jamaica,"154,740",,"3,536",,"102,761",,"48,443",,"51,838","1,185","1,183,986","396,633","2,985,094",North America,19,844,3,,,"16,228"
124,Cambodia,"138,726",,"3,056",,"135,670",,0,,"8,080",178,"3,091,420","180,062","17,168,639",Asia,124,"5,618",6,,,
125,Rwanda,"133,194",,"1,468",,"131,647",,79,,"9,793",108,"6,021,981","442,778","13,600,464",Africa,102,"9,265",2,,,6
126,Cameroon,"124,895",,"1,970",,"122,807",,118,13,"4,475",71,"1,751,774","62,762","27,911,548",Africa,223,"14,168",16,,,4
127,Malta,"118,317",,834,,"116,857",,626,4,"266,460","1,878","2,131,883","4,801,181","444,033",Europe,4,532,0,,,"1,410"
128,Barbados,"107,466",,588,,"106,869",,9,,"373,116","2,042","800,831","2,780,441","288,023",North America,3,490,0,,,31
129,Angola,"105,353",,"1,934",,"103,396",,23,,"3,008",55,"1,499,795","42,818","35,027,343",Africa,332,"18,111",23,,,0.7
130,Channel Islands,"101,717",,228,,"101,321",,168,,"576,421","1,292","1,252,808","7,099,551","176,463",Europe,2,774,0,,,952
131,French Guiana,"98,041",,420,,"11,254",,"86,367",6,"312,065","1,337","651,257","2,072,951","314,169",South America,3,748,0,,,"274,906"
132,DRC,"95,945",,"1,464",,"84,489",,"9,992",,"1,007",15,"846,704","8,890","95,240,792",Africa,993,"65,055",112,,,105
133,Senegal,"88,993",,"1,971",,"87,017",,5,,"5,041",112,"1,146,543","64,946","17,653,671",Africa,198,"8,957",15,,,0.3
134,Malawi,"88,722",,"2,686",,"85,644",,392,67,"4,396",133,"624,784","30,959","20,180,839",Africa,227,"7,513",32,,,19
135,Ivory Coast,"88,317",,834,,"87,479",,4,,"3,183",30,"1,688,277","60,856","27,742,298",Africa,314,"33,264",16,,,0.1
136,Suriname,"82,495",,"1,404",,N/A,N/A,N/A,,"138,222","2,352","241,666","404,915","596,831",South America,7,425,2,,,"52,502"
137,New Caledonia,"79,921",,314,,"79,600",,7,9,"274,723","1,079","98,964","340,182","290,915",Australia/Oceania,4,926,3,,,24
138,French Polynesia,"78,378",,649,,N/A,N/A,N/A,7,"275,820","2,284",,,"284,164",Australia/Oceania,4,438,,,,"155,646"
139,Eswatini,"74,586",,"1,425",,"73,088",,73,,"62,951","1,203","1,048,704","885,119","1,184,817",Africa,16,831,1,,,62
140,Guyana,"73,128",,"1,298",,"71,823",,7,,"92,096","1,635","727,430","916,107","794,045",South America,11,612,1,,,9
141,Belize,"70,782",,688,,"70,085",,9,6,"171,722","1,669","576,016","1,397,453","412,190",North America,6,599,1,,,22
142,Fiji,"68,918",,883,,"67,026",,"1,009",,"75,779",971,"670,477","737,221","909,466",Australia/Oceania,13,"1,030",1,,,"1,109"
143,Madagascar,"68,177",,"1,424",,"66,731",,22,,"2,337",49,"529,697","18,154","29,178,077",Africa,428,"20,490",55,,,0.8
144,Sudan,"63,993",,"5,046",,"58,617",,330,,"1,391",110,"562,941","12,240","45,992,020",Africa,719,"9,115",82,,,7
145,Mauritania,"63,715",,997,,"62,471",,247,,"12,998",203,"1,009,957","206,030","4,901,981",Africa,77,"4,917",5,,,50
146,Cabo Verde,"63,336",,413,,"62,832",,91,23,"111,570",728,"401,622","707,482","567,678",Africa,9,"1,375",1,,,160
147,Bhutan,"62,654",,21,,"61,564",,"1,069",,"79,516",27,"2,303,734","2,923,739","787,941",Asia,13,"37,521",0,,,"1,357"

In [7]:
# export to csv if needed
#df.to_csv('covid.csv')

In [12]:
# split the dataframe by continent
northamerica_df = df[df['Continent'] == 'North America']
southamerica_df = df[df['Continent'] == 'South America']
asia_df = df[df['Continent'] == 'Asia']
africa_df = df[df['Continent'] == 'Africa']
europe_df = df[df['Continent'] == 'Europe']
australia_df = df[df['Continent'] == 'Australia']

In [13]:
# show example
northamerica_df

,"Country,Other",TotalCases,NewCases,TotalDeaths,NewDeaths,TotalRecovered,NewRecovered,ActiveCases,"Serious,Critical",TotÂ Cases/1M pop,Deaths/1M pop,TotalTests,Tests/\n1M pop\n,Population,Continent,1 Caseevery X ppl,1 Deathevery X ppl,1 Testevery X ppl,New Cases/1M pop,New Deaths/1M pop,Active Cases/1M pop
#,,,,,,,,,,,,,,,,,,,,,
1,USA,"106,524,168",,"1,158,842",,"104,423,700",,"941,626","1,517","318,168","3,461","1,176,315,905","3,513,433","334,805,269",North America,3,289,0,,,"2,812"
19,Mexico,"7,572,705","+1,949","333,732",+14,"6,817,972",+871,"421,001",N/A,"57,560","2,537","19,870,676","151,036","131,562,772",North America,17,394,7,15,0.1,"3,200"
33,Canada,"4,641,301",,"52,247",,"4,569,105","+1,098","19,949",99,"120,904","1,361","66,343,123","1,728,207","38,388,419",North America,8,735,1,,,520
62,Guatemala,"1,247,237",,"20,189",,"1,226,129",,919,5,"67,113","1,086","7,179,223","386,311","18,584,039",North America,15,921,3,,,49
64,Costa Rica,"1,226,315",,"9,326",,"860,711",,"356,278",52,"236,633","1,800","4,659,757","899,158","5,182,354",North America,4,556,1,,,"68,748"
67,Cuba,"1,113,074",,"8,530",,"1,104,413",,131,2,"98,453",754,"14,344,078","1,268,753","11,305,652",North America,10,"1,325",1,,,12
71,Panama,"1,036,100",,"8,618",,"1,026,868",,614,16,"232,990","1,938","7,636,393","1,717,215","4,446,964",North America,4,516,1,,,138
82,Dominican Republic,"660,961",,"4,384",,"644,785",,"11,792",4,"59,781",397,"3,740,928","338,350","11,056,370",North America,17,"2,522",3,,,"1,067"
94,Honduras,"472,533",,"11,112",,N/A,N/A,N/A,105,"46,230","1,087","1,652,947","161,717","10,221,247",North America,22,920,6,,,"32,176"
111,Martinique,"229,807",,"1,098",,N/A,N/A,N/A,12,"614,314","2,935","828,928","2,215,870","374,087",North America,2,341,0,,,"611,101"
116,Guadeloupe,"202,364",,"1,015",,N/A,N/A,N/A,19,"506,171","2,539","938,039","2,346,306","399,794",North America,2,394,0,,,"498,004"
117,El Salvador,"201,785",,"4,230",,"179,410",,"18,145",8,"30,805",646,"2,610,114","398,467","6,550,389",North America,32,"1,549",3,,,"2,770"
118,Trinidad and Tobago,"191,350",,"4,387",,"186,918",,45,8,"136,039","3,119","911,009","647,674","1,406,585",North America,7,321,2,,,32
123,Jamaica,"154,740",,"3,536",,"102,761",,"48,443",,"51,838","1,185","1,183,986","396,633","2,985,094",North America,19,844,3,,,"16,228"
128,Barbados,"107,466",,588,,"106,869",,9,,"373,116","2,042","800,831","2,780,441","288,023",North America,3,490,0,,,31
141,Belize,"70,782",,688,,"70,085",,9,6,"171,722","1,669","576,016","1,397,453","412,190",North America,6,599,1,,,22
154,CuraÃ§ao,"45,986",,295,,"44,720",,971,3,"277,812","1,782","496,693","3,000,640","165,529",North America,4,561,0,,,"5,866"
155,Aruba,"44,114",,236,,"42,438",,"1,440",2,"409,947","2,193","177,885","1,653,068","107,609",North America,2,456,1,,,"13,382"
162,Bahamas,"38,003",,844,,"36,366",,793,1,"94,885","2,107","257,839","643,767","400,516",North America,11,475,2,,,"1,980"
165,Haiti,"34,221",,860,,"33,252",,109,,"2,930",74,"132,422","11,337","11,680,283",North America,341,"13,582",88,,,9
167,Cayman Islands,"31,472",,37,,"8,553",,"22,882",1,"467,797",550,"222,773","3,311,280","67,277",North America,2,"1,818",0,,,"340,116"
168,Saint Lucia,"30,052",,409,,"29,095",,548,,"162,344","2,209","210,983","1,139,752","185,113",North America,6,453,1,,,"2,960"
179,Grenada,"19,683",,238,,"19,358",,87,4,"173,457","2,097","182,981","1,612,523","113,475",North America,6,477,1,,,767
180,Bermuda,"18,860",,165,,"18,685",,10,,"304,493","2,664","1,029,558","16,622,128","61,939",North America,3,375,0,,,161
181,Nicaragua,"18,491",,225,,"4,225",,"14,041",,"2,728",33,,,"6,779,100",North America,367,"30,129",,,,"2,071"
189,Dominica,"15,760",,74,,"15,673",,13,,"217,848","1,023","229,344","3,170,187","72,344",North America,5,978,0,,,180
193,Saint Martin,"12,287",,63,,"1,399",,"10,825",7,"309,263","1,586","112,382","2,828,643","39,730",North America,3,631,0,,,"272,464"
195,Greenland,"11,971",,21,,"2,761",,"9,189",4,"210,117",369,"164,926","2,894,810","56,973",North America,5,"2,713",0,,,"161,287"
197,Caribbean Netherlands,"11,682",,38,,"10,476",,"1,168",,"438,398","1,426","30,126","1,130,559","26,647",North America,2,701,1,,,"43,832"
198,Sint Maarten,"11,030",,92,,"10,905",,33,N/A,"250,876","2,093","62,056","1,411,454","43,966",North America,4,478,1,,,751
201,St. Vincent Grenadines,"9,604",,124,,"9,478",,2,,"86,095","1,112","113,987","1,021,838","111,551",North America,12,900,1,,,18
203,Antigua and Barbuda,"9,106",,146,,"8,954",,6,1,"91,509","1,467","18,901","189,943","99,509",North America,11,682,5,,,60
208,British Virgin Islands,"7,305",,64,,N/A,N/A,N/A,,"238,757","2,092","107,339","3,508,269","30,596",North America,4,478,0,,,392
210,Saint Kitts and Nevis,"6,598",,48,,"6,550",,0,,"122,478",891,"126,939","2,356,351","53,871",North America,8,"1,122",0,,,
211,Turks and Caicos,"6,565",,38,,"6,509",,18,4,"165,195",956,"612,335","15,408,143","39,741",North America,6,"1,046",0,,,453
214,St. Barth,"5,484",,6,,N/A,N/A,N/A,,"551,433",603,"78,646","7,908,095","9,945",North America,2,"1,658",0,,,"504,374"
217,Anguilla,"3,904",,12,,"3,879",,13,4,"256,336",788,"51,382","3,373,736","15,230",North America,4,"1,269",0,,,854
219,Saint Pierre Miquelon,"3,452",,2,,"2,449",,"1,001",1,"599,410",347,"25,400","4,410,488","5,759",North America,2,"2,880",0,,,"173,815"
224,Montserrat,"1,403",,8,,"1,376",,19,,"282,578","1,611","17,762","3,577,442","4,965",North America,4,621,0,,,"3,827"